apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stevensp123/multi-server      
          ports:
            - containerPort: 5000
          env: 
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS__PORT
              value: '6379'
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD

      
